SELECT L.START_DATE, L.END_DATE, L.TOTAL, C.NAME, CA.NAME AS CAR_NAME, E.NAME AS EMPLOYEER_NAME
FROM LOCATIONS AS L
JOIN CUSTOMERS AS C
ON L.CUSTOMER_ID = C.ID
JOIN CARS AS CA
ON L.CAR_ID = CA.ID
JOIN EMPLOYEES AS E
ON L.EMPLOYEE_ID = E.ID;